/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CreateObjectDemo;
import CreateObjectDemo.CreateObjectDemoClass;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        CreateObjectDemoClass code = new CreateObjectDemoClass();
        code.COD();
    }

}
