/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FactoryPattern;

import com.sun.jdi.Method;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ShapeFactory shapeFactory = new ShapeFactory();

        // get an object of Circle and call its draw method.
        Shape circleShape = shapeFactory.getShape("Circle");
        // call draw method of Circle
        circleShape.draw();

        // get an object of Rectangle and call its draw method.
        Shape rectangleShape = shapeFactory.getShape("RECTANGLE");
        // call draw method of Rectangle
        rectangleShape.draw();

        // get an object of Square and call its draw method
        Shape squareShape = shapeFactory.getShape("square");
        // call draw method of Square
        squareShape.draw();
    }
}
