/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Counter;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        StartCounter ma = new StartCounter();
        ma.startThread();
    }
}
