/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bicycle;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      //   System.out.println(new App().getGreeting());
      MountainBike mb = new MountainBike(1, 2, 3, 4);
      mb.setSeatHeight(7);
      System.out.println("Tinggi tempat duduk sekarang adalah : " + mb.getSeatHeight());
    }
}

