/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Array_exists;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        Array_exists ae = new Array_exists();
        ae.printArrayExists();
    }
}
