/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NoAndUseStateCalculator;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        NoStateCalculator nsc = new NoStateCalculator();
        System.out.println(nsc.sum(7, 7));

        UseStateCalculator usc = new UseStateCalculator();
        System.out.println(usc.sum(7));

    }
}
