/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JsonVsXml;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        System.out.println("========READING XML FILE========");
        ReadXML readx = new ReadXML();
        readx.printXML();
        System.out.println("================================");

        System.out.println("========READING JSON FILE========");
        ReadJSON readjs = new ReadJSON();
        readjs.printJSON();
        System.out.println("=================================");
    }
}
